### ISSUE TITLE
ToC gets cut on small screens

### ISSUE THREAD

**Issue by icy-comet** [reorx/hugo-PaperModX#11]
The floating ToC gets cut on long articles if read with smaller screens.
Scrolling the page doesn't scroll the ToC, so that doesn't help either.

**Sample Screenshot**
![image](https://user-images.githubusercontent.com/50461557/163670363-9c1f101b-f429-4f38-8206-edd5c7730efa.png)

**Comment by reorx** [comment]
Hi @icy-comet, sorry for the late response, this should be fixed now, please check out to the latest commit.
