### ISSUE TITLE
[Feature request] Add "Pinned" icon when a post is pinned using `weight` front-matter

### ISSUE THREAD

**Issue by sethforprivacy** [reorx/hugo-PaperModX#14]
Could use the simple-icon for "Pinboard" as the icon if desired, but would be great for pinned posts to clearly reflect that (as normally posts are sorted by publish date):

```
<svg role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><title>Pinboard</title><path d="M13.352 14.585l-4.509 4.614.72-4.062L3.428 7.57 0 7.753 7.58 0v2.953l7.214 6.646 4.513-1.105-4.689 4.982L24 24l-10.648-9.415z"/></svg>
```

Could also just add `[pinned]` similar to how it's done with draft posts ATM (I'll see if I can do this myself).

**Comment by sethforprivacy** [comment]
Created a PR that adds "[Pinned]" when weight is specified: https://github.com/reorx/hugo-PaperModX/pull/15

**Comment by liaminw0** [comment]
how did you do this?
