### ISSUE TITLE
[BUG] The code in code block can't align with the line number in iOS mobile devices

### ISSUE THREAD

**Issue by Triple-Z** [reorx/hugo-PaperModX#22]
**Describe the bug**

 - Device/Os: iOS15.6
 - Type: Mobile
 - Browser and version [e.g. Chrome 86.0]: Safari, Firefox 103.1, Chrome 104.0
 - Hugo Version [ >=0.83.0 expected]: v0.101.0+extended
 - Theme Version [e.g. v4.0, master, or commit-id ]: 61452c190b57ed2c1246723e7fd1575ac4bf5a23

**Steps to reproduce the behavior:**

Use a browser(no matter what: Safari, Firefox or Chrome) in an iOS mobile device to open a page that has a least one code block with line numbers.

**Expected behavior**:

The code lines should align with the line numbers.

**Screenshots**

Safari: 
![image](https://user-images.githubusercontent.com/16285716/183888904-33763116-1cf4-497d-8015-b75b9841c813.png)

Firefox: 
![image](https://user-images.githubusercontent.com/16285716/183888970-36353ebf-b07d-48d8-9750-e722f6a78ee8.png)

Chrome: 
![image](https://user-images.githubusercontent.com/16285716/183889011-3968efb1-2d0b-47c5-8923-1deea63e22c8.png)

If you disable the `markup.highlight.lineNos` in `config.yaml`, the code is fine with line numbers:
![image](https://user-images.githubusercontent.com/16285716/183889347-622d6227-c5a6-4c38-8cdf-0cacc63962d6.png)

**Additional context**

If you need further testing, feel free to use this example page: https://58bed0b1.my-hugo-blog.pages.dev/posts/chaosblade-specific-cpu-load/

**Comment by drowzy** [comment]
I had a similar issue with variable font-sizes on ios devices. The fix outlined here: https://github.com/adityatelange/hugo-PaperMod/issues/828#issuecomment-1171994855 solved it for me. 

```
code {
    text-size-adjust: 100%;
    -ms-text-size-adjust: 100%;
    -moz-text-size-adjust: 100%;
    -webkit-text-size-adjust: 100%;
}
```

**Comment by Triple-Z** [comment]
@drowzy  thx very much, this solution works!
