### ISSUE TITLE
[BUG] The selected menu text color is the same as background in dark mode

### ISSUE THREAD

**Issue by Triple-Z** [reorx/hugo-PaperModX#44]
**Describe the bug**

 - Device/Os: [e.g. Android 10]
 - Type: [e.g. Desktop/Mobile]
 - Browser and version [e.g. Chrome 86.0]:
 - Hugo Version [ >=0.83.0 expected]:
 - Theme Version [e.g. v4.0, master, or commit-id ]:

**Steps to reproduce the behavior:**

**Expected behavior**:

**Screenshots**

<img width="1010" alt="image" src="https://user-images.githubusercontent.com/16285716/214048871-dcb82fc2-571b-4b22-a0ec-0dc9a0a4916d.png">

Like the screenshot above, the "归档" menu tag has disappeared when selected.

**Additional context**

**Comment by BeaCox** [comment]
hello, u can add a line`--signature: var(--tertitary);` to `PaperModX/assets/css/core/theme-vars.css`:
```
.dark {
......omitted here
    --signature: var(--tertitary);
}
```
Sure u can change var(--tertitary) to any color u like.
If u don't wanna change the file in the theme directory, u can create`site root/assets/css/core/` and copy the file just mentioned to that directory and make the changes.

**Comment by BeaCox** [comment]
This issue has been raised by others, refer:
#26 
#29

**Comment by Triple-Z** [comment]
Thanks a lot, looking forward to #29 to merge.
